---
title: "My 2010 all-decade album"
date: "2/11/2021"
categories: [music, art]
---

## Background

Reflecting back on music at the turn of a new decade gave me the idea for a challenge: if I could create one album with a maximum of 14 songs from the last decade, how would I construct it? Who would I pick? Looking at my list below reminds me just how much I have transformed since 2010. Just like the geological world, nothing is constant with me; change and evolution is commonplace. At the beginning of the decade, I had only heard of two artists on the list and actually only listened to one. I entered a hip hop fan who was always searching for the latest release to show my friends or commandeer the auxiliary cord at a party. By the end, I had blazed new trails; in fact, I nearly abandoned my comfort zone altogether.

Genres are really just paths waiting to be explored behind a closed door. These doors are usually opened by others -- sometimes yourself -- but, the decision to walk down the path is a personal one. In my case, my dad opened the doors to traditional blues and classic rock. Other doors were opened by friend's brothers, the radio, video games and so on. Despite those influences, I had never heard a metalcore song until the summer of 2016, when a couple of friends put on Unholy Confessions by Avenged Sevenfold as we travelled back from camping. I loved the standout riffs from all of the classic groups I had listened to up until that point, but that opening riff, that opening riff was different. The tone was heavier and the chord progression was everything I never knew I wanted. How someone could make a guitar sound in such a way was beyond my comprehension. The door had opened and my life changed - probably forever. Naturally, I found myself sprinting through the melodic death metal door shortly after. After walking both paths simultaneously, and almost religiously, over the last four years, I have created and continued to revise a personal quote (inspired by a YouTube comment) that succinctly describes my feelings:

> In the natural world, no genre of music shares a deeper connection to the primal state of being than metal. The abrasive brutality is strikingly clear, but it dances forward with precision and beauty. A unique, masterful performance displayed by no other. Within that raw, yet disciplined, power, a sensation of euphoric bliss and refined focus emerges.

Outside of the time constraint, the goal I had when making this track list was simple: take some of the best efforts from my favourite artists and create an album that flows well while also capturing the range of sound I have come to love. I knew how I wanted to structure the beginning and the end -- which ended up changing -- but it took some time to flesh out the heart of the album. Thirteen songs, fifty-four minutes and many listens later, I think I have something I will enjoy for many years. It contains some heavy, some melodic, some atmospheric, some catchy, some uplifting and some emotional. In particular, certain riffs (e.g., Killswitch Engage), solos (e.g., Darkest Hour, Shadows Fall) and choruses (e.g, Rise to Fall, Bury Tomorrow) still leave me with goosebumps after hundreds of listens. Additionally, I've left a few honourable mentions; they just did not integrate as well as I had initially thought. I've also left the Spotify link below.ยน

## Track list 

The Primeval Dark - Insomnium

While We Sleep - Insomnium

Acid Drops - Rise to Fall

Man on Fire - Bury Tomorrow

Save Your Soul - Shadows Fall

Echoes of the Fallen - Anterior

A New Dawn - In Flames

Truth Be Told - Phinehas

Turning Point - Killswitch Engage

Hypatia Rising - Darkest Hour

This Probably Won't End Well - All That Remains

Talk About Georgia - Jason Aldean

Coming Home - Avenged Sevenfold

## Honourable Mentions 

Twisted By Design - Sum 41

Rabbit Down The Hole - Billy Talent

My Own Grave - As I Lay Dying

Alpha Seed - ERRA

Based on my childhood foundation and fondness of the guitar, some would say I am exactly where I should be -- in a land where melody and power coexist and thrive.

For now,

MGW

------------------------------------------------------------------------

ยน [Spotify playlist](https://open.spotify.com/playlist/5aH2fKF7QafUMsxjF34Ngr?si=4d04e0e3a23c4439)
