project:
  type: website
  output-dir: docs

website:
  title: ""
format:
  html:
    theme: simplex
    css: styles.css
    mainfont: avenir next
    fontsize: 1rem
    fontcolor: "#3F3F3F"
    linkcolor: "#729fde"
    monofont: arial
    title-block-banner: true
    title-block-banner-color: "#000053"

editor: visual

